galaxy_info:
  author: Stephane Segning
  description: Role to install cargo
  company: adorsys GmbH & Co. KG
  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
    - name: Ubuntu
    - name: MacOSX

  galaxy_tags:
    - cargo
    - rust
    - rustup

  namespace: adorsys  
  role_name: cargo  

dependencies:
  - name: gis.laptop.common
